apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-producer-using-java-one-million-messages
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: redis-producer-using-java-one-million-messages
              image: miguelemos/lettuce_redis_stream_publisher:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: REDIS_HOST
                  value: "redis-redis-cluster"
                - name: MESSAGES_AMOUNT
                  value: "100000000"
                - name: MESSAGE
                  value: "hola desde la meeting con Nacho y Miguel"
          restartPolicy: OnFailure