
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-producer-using-java-one-million-messages
spec:
  template:
    # This is the pod template
    spec:
      containers:
        - name: redis-producer-using-java-one-million-messages
          image: miguelemos/lettuce_redis_stream_publisher:amd64
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "redis-redis-cluster"
            - name: MESSAGES_AMOUNT
              value: "100000000"
            - name: MESSAGE
              value: "hola desde la meeting con Nacho y Miguel"
      restartPolicy: OnFailure
      # The pod template ends here

